import './registerVscodeStub';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { test } from 'node:test';
import {
  composeWebviewFragments,
  INPUT_SCRIPT_FRAGMENTS,
  INPUT_STYLE_FRAGMENTS,
  INPUT_TEMPLATE_FRAGMENTS,
  type WebviewFragment
} from '../src/webview/input/composition';
import { getInputScript } from '../src/webview/input/script';
import { getInputStyles } from '../src/webview/input/styles';
import { getInputTemplate } from '../src/webview/input/template';
import { getScript } from '../src/webview/script';

test('input feature fragments compose deterministically and exactly once', () => {
  for (const fragments of [INPUT_SCRIPT_FRAGMENTS, INPUT_STYLE_FRAGMENTS, INPUT_TEMPLATE_FRAGMENTS]) {
    assert.equal(new Set(fragments).size, fragments.length);
    assert.equal(new Set(fragments.map((fragment) => fragment.id)).size, fragments.length);
    assert.ok(fragments.every((fragment) => fragment.id.length > 0 && fragment.source.length > 0));
    assert.equal(composeWebviewFragments(fragments), fragments.map((fragment) => fragment.source).join(''));
    assert.equal(composeWebviewFragments(fragments), composeWebviewFragments(fragments));
  }

  const duplicate: WebviewFragment = { id: 'duplicate', source: 'a' };
  assert.throws(
    () => composeWebviewFragments([duplicate, { id: 'duplicate', source: 'b' }]),
    /Duplicate or empty Webview fragment id/u
  );
});

test('modular input assembly preserves the pre-refactor generated bytes', () => {
  assert.equal(hash(getInputScript()), 'c45c30a11ddd531513163d77e1c1cad4407025bbd79569e1ab1002366634caa0');
  assert.equal(hash(getInputStyles()), 'ba8a097fed34835f63dea4c13d2efde2cd6c66625dda7d8220f2208206cf3ed8');
  assert.equal(hash(getInputTemplate()), '6dabc8c9fdbee55e8fcaa4d0de265d74277e124c4d94a435bcc1ad5229cfd220');
});

test('assembled input keeps unique DOM ids, public controls, payload fields, and feature CSS', () => {
  const template = getInputTemplate();
  const ids = [...template.matchAll(/\sid="([^"]+)"/gu)].map((match) => match[1]);
  assert.equal(new Set(ids).size, ids.length);
  assert.ok(template.indexOf('id="commandMenuButton"') < template.indexOf('id="goalButton"'));
  assert.match(template, /id="goalButton"[\s\S]*aria-haspopup="dialog"[\s\S]*id="goalHoverCard"/u);
  assert.match(template, /id="goalCreatePane"[\s\S]*id="goalManagePane"/u);
  assert.match(template, /id="goalDraftGenerationStatus"[\s\S]*id="goalGeneratedCriteria"[\s\S]*class="goal-advanced"/u);
  for (const key of [
    'goalCriterionWorkspaceState', 'goalCriterionValidation', 'goalCriterionArtifact', 'goalCriterionManual'
  ]) {
    assert.match(template, new RegExp(`data-i18n="${key}"`, 'u'));
  }
  assert.doesNotMatch(template, /id="goalRegion"/u);

  const script = getInputScript();
  const publicApiStart = script.indexOf('window.keepseekInputControls = {');
  const publicApiEnd = script.indexOf('};', publicApiStart);
  assert.ok(publicApiStart >= 0 && publicApiEnd > publicApiStart);
  const publicApi = script.slice(publicApiStart, publicApiEnd);
  for (const method of [
    'render',
    'renderUsage',
    'showSettingsDialog',
    'showHistorySettingsDialog',
    'showAboutDialog',
    'onSkillDraftCreated',
    'showStatus',
    'isPromptSubmittableEmpty',
    'clearPrompt'
  ]) {
    assert.match(publicApi, new RegExp(`\\b${method}:`, 'u'));
  }

  const submitStart = script.indexOf("composer.addEventListener('submit'");
  const submitEnd = script.indexOf("sendButton.addEventListener('click'", submitStart);
  const submit = script.slice(submitStart, submitEnd);
  for (const field of ['prompt', 'sourceId', 'modelId', 'settings', 'references', 'skillIds']) {
    assert.match(submit, new RegExp(`\\b${field}:`, 'u'));
  }
  assert.match(submit, /type: 'sendPrompt'/u);

  for (const messageType of [
    'openGoalDialog', 'generateGoalDraft', 'cancelGoalDraftGeneration', 'startGoal',
    'goalPause', 'goalResume', 'goalStop', 'goalClear', 'goalAmend', 'goalConfirmCriterion'
  ]) {
    assert.match(script, new RegExp(`type: '${messageType}'`, 'u'));
  }
  assert.match(script, /function renderGoalControls\(\)/u);
  assert.match(script, /function showGoalManager\(\)/u);
  assert.match(script, /goalResume\.disabled = state\.isBusy \|\| goalActionFeedback\?\.status === 'pending'/u);

  const styles = getInputStyles();
  for (const selector of [
    '.composer-input-inner',
    '.rich-file-link',
    '.reference-menu',
    '.skills-bar',
    '.command-menu',
    '.command-model-option',
    '.composer-goal-btn',
    '.goal-hover-card',
    '.goal-generation-status',
    '.goal-generated-criterion',
    '.goal-advanced',
    '.goal-manage-pane',
    '.context-progress',
    '.usage-details-dialog',
    '.settings-overlay',
    '.settings-account-workspace',
    '.about-details',
    '.new-account-provider-menu'
  ]) {
    assert.ok(styles.includes(selector), `missing ${selector}`);
  }

  assert.doesNotThrow(() => new Function(script));
  assert.doesNotThrow(() => new Function(getScript()));
});

function hash(value: string): string {
  return createHash('sha256').update(value).digest('hex');
}
