import './registerVscodeStub';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { test } from 'node:test';
import {
  composeWebviewFragments,
  INPUT_SCRIPT_FRAGMENTS,
  INPUT_STYLE_FRAGMENTS,
  INPUT_TEMPLATE_FRAGMENTS,
  type WebviewFragment
} from '../src/webview/input/composition';
import { getInputScript } from '../src/webview/input/script';
import { getInputStyles } from '../src/webview/input/styles';
import { getInputTemplate } from '../src/webview/input/template';
import { getScript } from '../src/webview/script';

test('input feature fragments compose deterministically and exactly once', () => {
  for (const fragments of [INPUT_SCRIPT_FRAGMENTS, INPUT_STYLE_FRAGMENTS, INPUT_TEMPLATE_FRAGMENTS]) {
    assert.equal(new Set(fragments).size, fragments.length);
    assert.equal(new Set(fragments.map((fragment) => fragment.id)).size, fragments.length);
    assert.ok(fragments.every((fragment) => fragment.id.length > 0 && fragment.source.length > 0));
    assert.equal(composeWebviewFragments(fragments), fragments.map((fragment) => fragment.source).join(''));
    assert.equal(composeWebviewFragments(fragments), composeWebviewFragments(fragments));
  }

  const duplicate: WebviewFragment = { id: 'duplicate', source: 'a' };
  assert.throws(
    () => composeWebviewFragments([duplicate, { id: 'duplicate', source: 'b' }]),
    /Duplicate or empty Webview fragment id/u
  );
});

test('modular input assembly preserves the reviewed generated bytes', () => {
  assert.equal(hash(getInputScript()), '23d2d9a913a1b82681d9f86612b03ae88d75a1e2cbec1bdfd5a8c1fe1362f8f2');
  assert.equal(hash(getInputStyles()), '3d8a2512560ccc3e4bcdb951d6bd66e72be663b79622000a66000379519ce1d0');
  assert.equal(hash(getInputTemplate()), '5a9fec94a7dfa064aa89538629fead7301619ee450a1235759be97c56c4aba47');
});

test('assembled input keeps unique DOM ids, public controls, payload fields, and feature CSS', () => {
  const template = getInputTemplate();
  const ids = [...template.matchAll(/\sid="([^"]+)"/gu)].map((match) => match[1]);
  assert.equal(new Set(ids).size, ids.length);

  const script = getInputScript();
  const publicApiStart = script.indexOf('window.keepseekInputControls = {');
  const publicApiEnd = script.indexOf('};', publicApiStart);
  assert.ok(publicApiStart >= 0 && publicApiEnd > publicApiStart);
  const publicApi = script.slice(publicApiStart, publicApiEnd);
  for (const method of [
    'render',
    'renderUsage',
    'showSettingsDialog',
    'showHistorySettingsDialog',
    'showAboutDialog',
    'onSkillDraftCreated',
    'showStatus',
    'isPromptSubmittableEmpty',
    'clearPrompt'
  ]) {
    assert.match(publicApi, new RegExp(`\\b${method}:`, 'u'));
  }

  const submitStart = script.indexOf("composer.addEventListener('submit'");
  const submitEnd = script.indexOf("sendButton.addEventListener('click'", submitStart);
  const submit = script.slice(submitStart, submitEnd);
  for (const field of ['prompt', 'sourceId', 'modelId', 'settings', 'references', 'skillIds']) {
    assert.match(submit, new RegExp(`\\b${field}:`, 'u'));
  }
  assert.match(submit, /type: 'sendPrompt'/u);

  const styles = getInputStyles();
  for (const selector of [
    '.composer-input-inner',
    '.rich-file-link',
    '.reference-menu',
    '.skills-bar',
    '.command-menu',
    '.command-model-option',
    '.context-progress',
    '.usage-details-dialog',
    '.settings-overlay',
    '.settings-account-workspace',
    '.about-details',
    '.new-account-provider-menu'
  ]) {
    assert.ok(styles.includes(selector), `missing ${selector}`);
  }

  assert.doesNotThrow(() => new Function(script));
  assert.doesNotThrow(() => new Function(getScript()));
});

function hash(value: string): string {
  return createHash('sha256').update(value).digest('hex');
}
